#!/home/khaleb.dabakuyo@Digital-Grenoble.local/anaconda3/envs/Othello_env/bin/python3.9
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
